# Copy this file to cinchbot.yml and make the appropriate modifications.

# Our main bot run dir, directories listed below will be relative to this
# unless a full path is given.
dir_main: ~/cinchbot

# Plugin directories
plugins:
  core:  plugins/core
  extra: plugins/enabled

# The networks we'll connect to

  freenode:
    server: irc.freenode.net
    nicks: [		"ponydestroyer", 
                "albator2088", 
                "bananatorz", 
                "pot_a_toe", 
                "sslipzor", 
                "neinnonon", 
                "oignonringo", 
                "cheveu2feu", 
                "blabliblouz", 
                "proutozorus", 
                "tirlipimpon", 
                "foufinoufoufou", 
                "bonhome_en_mousse", 
                "polakvampire", 
                "vvvvvvvvvvv", 
                "_underscoretaker_", 
                "BulkGloghan", 
                "maskedpotato", 
                "poupipoupipou", 
                "octopidou", 
                "popopokaface", 
                "modafuda69"]

    channels:
      - '#go'

   
